package com.img.nirbhayx.utils

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import com.img.nirbhayx.R
import com.img.nirbhayx.data.SafetyTip
import java.io.File
import java.io.FileWriter

object SafetyTipActions {

    fun shareTip(context: Context, tip: SafetyTip) {
        val shareText = buildString {
            appendLine(getStringByName(context, tip.titleKey))
            appendLine()
            appendLine(getStringByName(context, tip.contentKey))

            tip.steps?.let { steps ->
                appendLine()
                appendLine(context.getString(R.string.steps_to_follow))
                steps.forEachIndexed { index, step ->
                    appendLine("${index + 1}. $step")
                }
            }

            tip.emergencyNumbers?.let { numbers ->
                appendLine()
                appendLine(context.getString(R.string.emergency_numbers))
                numbers.forEach { number ->
                    appendLine("📞 $number")
                }
            }

            appendLine()
            appendLine("Shared via NirbhayX - Your Safety Companion")
        }

        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, shareText)
            putExtra(Intent.EXTRA_SUBJECT, getStringByName(context, tip.titleKey))
        }

        context.startActivity(Intent.createChooser(shareIntent, "Share Safety Tip"))
    }

    fun saveTipAsFile(context: Context, tip: SafetyTip) {
        try {
            val fileName = "safety_tip_${tip.id}.txt"
            val file = File(context.getExternalFilesDir(null), fileName)

            FileWriter(file).use { writer ->
                writer.write(buildTipContent(context, tip))
            }

            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            context.startActivity(Intent.createChooser(intent, "Save Safety Tip"))

        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    fun makeEmergencyCall(context: Context, number: String) {
        val intent = Intent(Intent.ACTION_CALL).apply {
            data = Uri.parse("tel:$number")
        }

        if (intent.resolveActivity(context.packageManager) != null) {
            context.startActivity(intent)
        } else {
            val dialIntent = Intent(Intent.ACTION_DIAL).apply {
                data = Uri.parse("tel:$number")
            }
            context.startActivity(dialIntent)
        }
    }

    private fun buildTipContent(context: Context, tip: SafetyTip): String {
        return buildString {
            appendLine("🛡️ ${getStringByName(context, tip.titleKey)}")
            appendLine("=".repeat(50))
            appendLine()
            appendLine("📋 Description:")
            appendLine(getStringByName(context, tip.contentKey))
            appendLine()

            tip.steps?.let { steps ->
                appendLine("📝 Steps to Follow:")
                steps.forEachIndexed { index, step ->
                    appendLine("${index + 1}. $step")
                }
                appendLine()
            }

            tip.emergencyNumbers?.let { numbers ->
                appendLine("📞 Emergency Numbers:")
                numbers.forEach { number ->
                    appendLine("• $number")
                }
                appendLine()
            }

            appendLine("🏷️ Category: ${getStringByName(context, tip.category.displayNameKey)}")
            appendLine()
            appendLine("Generated by NirbhayX - Your Safety Companion")
            appendLine("Stay Safe, Stay Prepared!")
        }
    }
}

fun getStringByName(context: Context, key: String): String {
    val resId = context.resources.getIdentifier(key, "string", context.packageName)
    return if (resId != 0) context.getString(resId) else key
}
